export const LOAD_EMPLOYER_SUCCESS = 'LOAD_EMPLOYER_SUCCESS';
export const ADD_EMPLOYER_SUCCESS = 'ADD_EMPLOYER_SUCCESS';
export const UPDATE_EMPLOYER_SUCCESS = 'UPDATE_EMPLOYER_SUCCESS';
export const DELETE_EMPLOYER_SUCCESS = 'DELETE_EMPLOYER_SUCCESS';
export const ADD_REVIEW = 'ADD_REVIEW';
export const UPDATE_REVIEW = 'UPDATE_REVIEW';
export const DELETE_REVIEW = 'DELETE_REVIEW';
export const BEGIN_API_CALL = 'BEGIN_API_CALL';