name: app

dependencies:
  - python=3.6
  - psycopg2
  - pip:
      - coreapi==2.3.3
      - Django==2.2.2
      - djangorestframework==3.9.4
      - django-filter==2.1.0
      - djangorestframework_simplejwt==4.3.0
      - flake8
      - gunicorn==19.9.0
      - markdown==3.1.1
      - Pygments==2.4.2
